### ISSUE TITLE
cannot send mail  to multiple bcc and  cc email

### ISSUE THREAD

**Issue by pritku** [WadeShuler/yii2-sendgrid#5]
cannot send mail  to multiple **bcc** and  **cc** email
 it generates bad request error
by using **sendgrid** defaullt api we can add multiple bcc email 
but using your plugin ot generates error
it only accepts single **bcc** ,**cc** email

**Comment by WadeShuler** [comment]
I will try and get back to this in the next few days. Probably over the weekend.

What version of the Yii2 framework are you on?
Basic or Advanced?
What version of PHP?

Since you already seem to have an environment ready where you can test a few things out, can you answer the following questions please?

Does a single BCC and single CC work (one of each, both in the same message)?
Does multiple BCC work (no CC)?
Does multiple CC work (no BCC)?
Does multiple BCC and single CC work?
Does single BCC and multiple CC work?

**Comment by pritku** [comment]
my yii2 version is 2.0.32 advanced
php version 7.3

i think your code  in Message.php in src folder
in `buildMessage` function

`               // Single Send Mode`
                ` $personalization = new \SendGrid\Personalization();`

                if ( is_array($this->to) ) {
                    foreach ($this->to as $key => $val) {
                        if ( is_int($key) ) {
                            // `[0 => email]`
                            $personalization->addTo( new \SendGrid\Email(null, $val) );
                        } else {
                            // `[email => name]`
                            $personalization->addTo( new \SendGrid\Email($val, $key) );
                        }
                    }
                } else {
                    $personalization->addTo( new \SendGrid\Email(null, $this->to) );
                }`


in this line u are using single bcc
i have copied to `personalisation `code for `bcc `then it starts working for multiple bcc
i think you can update your  plugin for multiple `bcc `and `cc`
in my code i used multiple to ,multiple bcc and no cc

**Comment by abdouTurki** [comment]
I faced the same bug, I did as @pritku suggested and it works

**Comment by WadeShuler** [comment]
Please update to version 1.0.3 and let me know if it solves it for you.

**Comment by abdouTurki** [comment]
Okey will do next deploy, but it should work I did the same changes you did and it works for me.

**Comment by pritku** [comment]
its working thanks
